var MSG = {
  title: "Code",
  blocks: "Blocks",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Run the program defined by the blocks in the workspace.",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard all blocks.",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  catInitializes: "Initializes",
  catInout: "In/Out",
	catDigital: "Digital",
	catAnalog: "Analog",
  catOthers: "Others",
  catTimes: "Time",
	catSerial: "Serial",
  catInterrupts: "Interrupts",
	catAdafruit: "Adafruit",
  catRgbLed: "RGBLed(ws8211)",
	catNeoPixel: "Neopixel",
	catI2cMatrix: "Led Matrix",
	catI2cSevenseg: "7 Segment",
	catMpr121: "Capatitive Sensor",
	catGrove: "Grove",
	catGroveInput: "Grove Input",
	catGroveOutput: "Grove Output",
	catGroveSensor: "Grove Sensors",
  catGrovergbLCD: "Grove RGB LCD",
  catRobot: "Robot",
  catShieldbot: "ShieldBot",
  catAerobot: "AERobot",
  catEthernet: "Ethernet",
  catEthernetInit: "Init",
  catEthernetClient: "Client",
  catCloudService: "Cloud Service",
  catIFTTT: "IFTTT",
  catM2x: "M2X",
  catBlynk: "Blynk",
  catServo: "Servo",
	catUltraSonic: "Ultra Sonic",
	catOtherSensor: "Other Sensor",
	catInvolt: "involt",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML."
};
